.TH JEF 1
.SH NAME
jef \- a lossless file compression utility
.SH SYNOPSIS
.B jef
[\fB\-r\fR]
.IR file
.SH DESCRIPTION
The
.B jef
utility uses the Huffman coding algorithm to losslessly compress files. It outputs...
.SH OPTIONS
.TP
.BR \-r
TODO
.SH EXIT STATUS
The
.B jef
utility returns 0 on success, and 1 on failure.
.SH AUTHOR
.B jef
was written by Jeffin Jacob.
